package schemalock

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

func TestParseSQLProducesDeterministicPortableLock(t *testing.T) {
	sources := map[string]string{
		"sqlite": `
CREATE TABLE categories (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);
CREATE TABLE products (
  id INTEGER PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories(id),
  name TEXT NOT NULL,
  price REAL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  payload BLOB,
  UNIQUE (name, active)
);
`,
		"postgresql": `
CREATE TABLE public.categories (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL,
  name CHARACTER VARYING(100) NOT NULL,
  price NUMERIC(10, 2),
  active BOOLEAN NOT NULL DEFAULT FALSE,
  payload BYTEA,
  CONSTRAINT products_category_fk FOREIGN KEY (category_id) REFERENCES public.categories (id)
);
CREATE UNIQUE INDEX products_name_active ON public.products (name, active);
`,
		"mysql": `
CREATE TABLE categories (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE products (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT NOT NULL,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10, 2) NULL,
  active BOOLEAN NOT NULL DEFAULT FALSE,
  payload BLOB,
  CONSTRAINT products_category_fk FOREIGN KEY (category_id) REFERENCES categories (id),
  UNIQUE KEY products_name_active (name, active)
);
`,
	}
	for adapter, source := range sources {
		t.Run(adapter, func(t *testing.T) {
			lock, err := ParseSQL(adapter, []byte(source))
			if err != nil {
				t.Fatal(err)
			}
			products := lock.Tables["products"]
			if len(products.Columns) != 6 {
				t.Fatalf("columns=%#v", products.Columns)
			}
			if id := products.Columns["id"]; id.Type != "Integer" || !id.PrimaryKey || !id.Generated || id.Nullable {
				t.Fatalf("id=%#v", id)
			}
			if price := products.Columns["price"]; price.Type != "Float" || !price.Nullable {
				t.Fatalf("price=%#v", price)
			}
			if payload := products.Columns["payload"]; payload.Type != "Bytes" {
				t.Fatalf("payload=%#v", payload)
			}
			foreignKey := products.ForeignKeys[ForeignKeyKey("category_id", "categories", "id")]
			if foreignKey.Column != "category_id" {
				t.Fatalf("foreign keys=%#v", products.ForeignKeys)
			}
			if unique := products.UniqueConstraints[ConstraintKey(false, []string{"name", "active"})]; len(unique.Columns) != 2 {
				t.Fatalf("unique constraints=%#v", products.UniqueConstraints)
			}
			first, err := lock.Bytes()
			if err != nil {
				t.Fatal(err)
			}
			second, err := lock.Bytes()
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(first, second) {
				t.Fatal("schema lock encoding is not deterministic")
			}
			if bytes.Contains(first, []byte(`"database":`)) || bytes.Contains(first, []byte("databaseType")) || bytes.Contains(first, []byte("generatedAt")) {
				t.Fatalf("lock contains volatile metadata: %s", first)
			}
		})
	}
}

func TestParseSQLAcceptsPortableDateTimeTypes(t *testing.T) {
	for adapter, source := range map[string]string{
		"sqlite":     "CREATE TABLE events (id INTEGER PRIMARY KEY, on_date DATE, at_time TIME, local_at DATETIME, exact_at TIMESTAMPTZ);",
		"postgresql": "CREATE TABLE events (id BIGSERIAL PRIMARY KEY, on_date DATE, at_time TIME, local_at TIMESTAMP, exact_at TIMESTAMPTZ);",
		"mysql":      "CREATE TABLE events (id BIGINT AUTO_INCREMENT PRIMARY KEY, on_date DATE, at_time TIME(6), local_at DATETIME(6), exact_at TIMESTAMP(6));",
	} {
		t.Run(adapter, func(t *testing.T) {
			lock, err := ParseSQL(adapter, []byte(source))
			if err != nil {
				t.Fatal(err)
			}
			for name, want := range map[string]string{"on_date": "Date", "at_time": "TimeOfDay", "local_at": "DateTime", "exact_at": "Instant"} {
				if got := lock.Tables["events"].Columns[name].Type; got != want {
					t.Fatalf("%s type=%s, want %s", name, got, want)
				}
			}
		})
	}
}

func TestParseSQLAcceptsSqldefExportShapes(t *testing.T) {
	postgresql := `
CREATE TABLE "public"."categories" (
  "id" bigserial NOT NULL,
  "name" text NOT NULL,
  CONSTRAINT categories_pkey PRIMARY KEY ("id")
);
CREATE TABLE "public"."products" (
  "id" bigserial NOT NULL,
  "category_id" bigint NOT NULL,
  "name" character varying(100) NOT NULL,
  CONSTRAINT products_pkey PRIMARY KEY ("id")
);
ALTER TABLE "public"."categories" ADD CONSTRAINT "categories_name_key" UNIQUE (name);
ALTER TABLE ONLY "public"."products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "public"."products" ADD CONSTRAINT "products_name_key" UNIQUE (name);
`
	lock, err := ParseSQL("postgresql", []byte(postgresql))
	if err != nil {
		t.Fatal(err)
	}
	products := lock.Tables["products"]
	if len(products.ForeignKeys) != 1 || len(products.UniqueConstraints) != 2 {
		t.Fatalf("PostgreSQL exported constraints=%#v %#v", products.ForeignKeys, products.UniqueConstraints)
	}

	mysql := `
CREATE TABLE products (
  id bigint NOT NULL AUTO_INCREMENT,
  category_id bigint NOT NULL,
  name varchar(100) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY name (name),
  KEY category_id (category_id)
);
`
	lock, err = ParseSQL("mysql", []byte(mysql))
	if err != nil {
		t.Fatal(err)
	}
	if len(lock.Tables["products"].UniqueConstraints) != 2 {
		t.Fatalf("MySQL exported constraints=%#v", lock.Tables["products"].UniqueConstraints)
	}
}

func TestSchemaLockRoundTripsAndRejectsUnknownFields(t *testing.T) {
	lock, err := ParseSQL("sqlite", []byte("CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT NOT NULL);"))
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "db", "schema.lock.json")
	if err := lock.Write(path); err != nil {
		t.Fatal(err)
	}
	loaded, err := Read(path)
	if err != nil {
		t.Fatal(err)
	}
	equal, err := Equal(lock, loaded)
	if err != nil || !equal {
		t.Fatalf("equal=%v err=%v", equal, err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	invalid := bytes.Replace(data, []byte(`"adapter": "sqlite"`), []byte(`"adapter": "sqlite", "generatedAt": "now"`), 1)
	if err := os.WriteFile(path, invalid, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := Read(path); err == nil {
		t.Fatal("unknown lock field was accepted")
	}
}
