// Package nativepackage owns cached type information derived from native
// target-language packages. The cache is generated by trb install and keeps
// native declaration parsing out of ordinary compiler and language-service
// requests.
package nativepackage

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"

	"github.com/type-rb/type-rb/internal/types"
)

const (
	FormatVersion     = 1
	indexRelativePath = ".trb/native-types.json"
)

type Catalog struct {
	FormatVersion     int               `json:"formatVersion"`
	TypeScriptVersion string            `json:"typescriptVersion,omitempty"`
	Dependencies      map[string]string `json:"dependencies"`
	ProviderChecksums map[string]string `json:"providerChecksums,omitempty"`
	Modules           map[string]Module `json:"modules"`
	UnavailableReason string            `json:"-"`
}

type Module struct {
	Exports     map[string]Export `json:"exports"`
	Records     map[string]Export `json:"records,omitempty"`
	Unsupported map[string]string `json:"unsupported,omitempty"`
}

type Export struct {
	Kind              string            `json:"kind"`
	Type              Type              `json:"type"`
	AliasTarget       *Type             `json:"aliasTarget,omitempty"`
	Parameters        []Type            `json:"parameters,omitempty"`
	Required          int               `json:"required,omitempty"`
	Variadic          bool              `json:"variadic,omitempty"`
	TypeParameters    []string          `json:"typeParameters,omitempty"`
	Fields            []Field           `json:"fields,omitempty"`
	UnsupportedFields map[string]string `json:"unsupportedFields,omitempty"`
}

type Field struct {
	Name     string `json:"name"`
	Type     Type   `json:"type"`
	Optional bool   `json:"optional,omitempty"`
}

// Type is the stable on-disk form of a target-independent semantic type.
type Type struct {
	Kind         string `json:"kind"`
	Name         string `json:"name,omitempty"`
	Args         []Type `json:"args,omitempty"`
	Fails        *Type  `json:"fails,omitempty"`
	EffectBridge string `json:"effectBridge,omitempty"`
	Nullable     bool   `json:"nullable,omitempty"`
	Readonly     bool   `json:"readonly,omitempty"`
}

func (t Type) Semantic() types.Type {
	result := types.Type{Kind: types.Kind(t.Kind), Name: t.Name, Nullable: t.Nullable, Readonly: t.Readonly}
	for _, argument := range t.Args {
		result.Args = append(result.Args, argument.Semantic())
	}
	if t.Fails != nil {
		failure := t.Fails.Semantic()
		result.Fails = &failure
	}
	if result.Name == "" {
		result.Name = types.FromName(string(result.Kind)).Name
	}
	return result
}

func FromSemantic(typ types.Type) Type {
	result := Type{Kind: string(typ.Kind), Name: typ.Name, Nullable: typ.Nullable, Readonly: typ.Readonly}
	for _, argument := range typ.Args {
		result.Args = append(result.Args, FromSemantic(argument))
	}
	if typ.Fails != nil {
		failure := FromSemantic(*typ.Fails)
		result.Fails = &failure
	}
	return result
}

func IndexPath(root string) string {
	return filepath.Join(root, filepath.FromSlash(indexRelativePath))
}

func Empty(dependencies map[string]string) *Catalog {
	return &Catalog{FormatVersion: FormatVersion, Dependencies: cloneDependencies(dependencies), Modules: map[string]Module{}}
}

func Load(root string, dependencies map[string]string) (*Catalog, error) {
	return load(root, dependencies, nil, false)
}

func LoadWithProviders(root string, dependencies map[string]string, providers []ProviderSource) (*Catalog, error) {
	expectedProviders, err := providerChecksums(providers)
	if err != nil {
		return nil, err
	}
	return load(root, dependencies, expectedProviders, true)
}

func load(root string, dependencies, providers map[string]string, checkProviders bool) (*Catalog, error) {
	expected := cloneDependencies(dependencies)
	if len(expected) == 0 {
		return Empty(nil), nil
	}
	data, err := os.ReadFile(IndexPath(root))
	if errors.Is(err, os.ErrNotExist) {
		catalog := Empty(expected)
		catalog.UnavailableReason = "native TypeScript package types are not indexed; run trb install"
		return catalog, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read native TypeScript package index: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var catalog Catalog
	if err := decoder.Decode(&catalog); err != nil {
		return nil, fmt.Errorf("decode %s: %w", IndexPath(root), err)
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		return nil, fmt.Errorf("decode %s: trailing JSON content", IndexPath(root))
	}
	if catalog.FormatVersion != FormatVersion {
		return nil, fmt.Errorf("%s uses unsupported formatVersion %d; run trb install", IndexPath(root), catalog.FormatVersion)
	}
	if catalog.Modules == nil {
		catalog.Modules = map[string]Module{}
	}
	if !equalDependencies(catalog.Dependencies, expected) {
		catalog.Dependencies = expected
		catalog.Modules = map[string]Module{}
		catalog.UnavailableReason = "native TypeScript package types are stale; run trb install"
	}
	if checkProviders && !equalDependencies(catalog.ProviderChecksums, providers) {
		catalog.ProviderChecksums = cloneDependencies(providers)
		catalog.Modules = map[string]Module{}
		catalog.UnavailableReason = "native TypeScript package provider types are stale; run trb install"
	}
	return &catalog, nil
}

func Write(root string, catalog *Catalog) error {
	if catalog == nil {
		catalog = Empty(nil)
	}
	catalog.FormatVersion = FormatVersion
	if catalog.Dependencies == nil {
		catalog.Dependencies = map[string]string{}
	}
	if catalog.ProviderChecksums == nil {
		catalog.ProviderChecksums = map[string]string{}
	}
	if catalog.Modules == nil {
		catalog.Modules = map[string]Module{}
	}
	data, err := json.MarshalIndent(catalog, "", "  ")
	if err != nil {
		return fmt.Errorf("encode native TypeScript package index: %w", err)
	}
	data = append(data, '\n')
	path := IndexPath(root)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".native-types-*.json")
	if err != nil {
		return err
	}
	temporaryName := temporary.Name()
	defer func() { _ = os.Remove(temporaryName) }()
	if _, err := temporary.Write(data); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Chmod(0o644); err != nil {
		_ = temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	if err := os.Rename(temporaryName, path); err != nil {
		return err
	}
	return nil
}

func (c *Catalog) Owns(importPath string) bool {
	if c == nil {
		return false
	}
	for dependency := range c.Dependencies {
		if importPath == dependency || len(importPath) > len(dependency) && importPath[:len(dependency)+1] == dependency+"/" {
			return true
		}
	}
	return false
}

func (c *Catalog) Module(importPath string) (Module, bool) {
	if c == nil {
		return Module{}, false
	}
	module, ok := c.Modules[importPath]
	return module, ok
}

func cloneDependencies(input map[string]string) map[string]string {
	result := make(map[string]string, len(input))
	keys := make([]string, 0, len(input))
	for name := range input {
		keys = append(keys, name)
	}
	sort.Strings(keys)
	for _, name := range keys {
		result[name] = input[name]
	}
	return result
}

func equalDependencies(left, right map[string]string) bool {
	if len(left) != len(right) {
		return false
	}
	for name, version := range left {
		if right[name] != version {
			return false
		}
	}
	return true
}
