package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/type-rb/type-rb/internal/compiler"
	packageManager "github.com/type-rb/type-rb/internal/packages"
	"github.com/type-rb/type-rb/internal/project"
)

func TestWebClientGeneratesTheSameTypeRBSourceAcrossBackendModes(t *testing.T) {
	var baseline string
	for _, mode := range []string{"go", "ruby", "typescript"} {
		t.Run(mode, func(t *testing.T) {
			root := t.TempDir()
			config := project.New(root, mode)
			config.Name = "reports-api"
			config.Version = "2.4.0"
			config.SourceDir = "src"
			if config.Go != nil {
				config.Go.Module = "example.com/type-rb/web-client-test"
			}
			if err := config.Save(); err != nil {
				t.Fatal(err)
			}
			writeOpenAPIProject(t, root)

			var stdout, stderr bytes.Buffer
			command := &CLI{Stdin: strings.NewReader(""), Stdout: &stdout, Stderr: &stderr}
			if status := command.Run([]string{"web", "client", "--config", config.Path, "--name", "ReportsClient"}); status != 0 {
				t.Fatalf("status=%d stderr=%s", status, stderr.String())
			}
			source := stdout.String()
			for _, fragment := range []string{
				"# Generated by trb web client. Do not edit.",
				"class ReportsClient",
				"def create_report(input: CreateReportInput, *, headers: Headers = Headers.new(), timeout_milliseconds: Integer? = nil)",
				`path := "/" + "reports" + "/" + URL.encode_component(input.params.id.value().to_s())`,
				"body := try json_body(input.body)",
				"Status202(response: Response<CreateReportResponse>)",
			} {
				if !strings.Contains(source, fragment) {
					t.Fatalf("generated source does not contain %q:\n%s", fragment, source)
				}
			}
			if mode == "go" {
				baseline = source
			} else if source != baseline {
				t.Fatalf("%s browser client differs from Go:\n%s\n--- Go ---\n%s", mode, source, baseline)
			}
			if stderr.Len() != 0 {
				t.Fatalf("unexpected stderr: %s", stderr.String())
			}
		})
	}
}

func TestWebClientWritesBelowTheProjectRootAndCompilesForBrowser(t *testing.T) {
	root := t.TempDir()
	config := project.New(root, "go")
	config.SourceDir = "src"
	config.Go.Module = "example.com/type-rb/web-client-output-test"
	if err := config.Save(); err != nil {
		t.Fatal(err)
	}
	writeOpenAPIProject(t, root)

	var stdout, stderr bytes.Buffer
	command := &CLI{Stdin: strings.NewReader(""), Stdout: &stdout, Stderr: &stderr}
	if status := command.Run([]string{"web", "client", "--config", config.Path, "--output", "generated/api_client.trb"}); status != 0 {
		t.Fatalf("status=%d stderr=%s", status, stderr.String())
	}
	path := filepath.Join(root, "generated", "api_client.trb")
	if stdout.String() != path+"\n" {
		t.Fatalf("stdout=%q, want output path", stdout.String())
	}
	generated, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	contracts, err := os.ReadFile(filepath.Join(root, "src", "contracts", "reports.trb"))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := compiler.CompileProject([]compiler.SourceUnit{
		{Filename: "/browser/src/contracts/reports.trb", ModulePath: "contracts/reports", Source: contracts},
		{Filename: "/browser/src/generated/api_client.trb", ModulePath: "generated/api_client", Source: generated},
	}, compiler.Options{Mode: "typescript", TypeScriptRuntime: "browser", ProjectRoot: "/browser", SourceRoot: "/browser/src"}); err != nil {
		t.Fatalf("generated source did not compile for the browser target: %v\n%s", err, generated)
	}

	stderr.Reset()
	if status := command.Run([]string{"web", "client", "--config", config.Path, "--output", "../outside.trb"}); status == 0 || !strings.Contains(stderr.String(), "path cannot escape") {
		t.Fatalf("escaping output path status=%d stderr=%s", status, stderr.String())
	}
}

func TestWebClientGeneratesFromContractTypesInLocalPackage(t *testing.T) {
	for _, mode := range []string{"go", "ruby", "typescript"} {
		t.Run(mode, func(t *testing.T) {
			workspace := t.TempDir()
			packageRoot := filepath.Join(workspace, "contracts")
			if err := os.MkdirAll(filepath.Join(packageRoot, "src"), 0o755); err != nil {
				t.Fatal(err)
			}
			manifest := `{"formatVersion":1,"name":"github.com/acme/contracts","version":"0.1.0","sourceDir":"src"}
`
			if err := os.WriteFile(filepath.Join(packageRoot, "trbpackage.json"), []byte(manifest), 0o644); err != nil {
				t.Fatal(err)
			}
			contracts := `newtype ReportID = Integer

record ReportParams
	id: ReportID
end

record GetReportInput
	params: ReportParams
end

record ReportResponse
	id: ReportID
end
`
			if err := os.WriteFile(filepath.Join(packageRoot, "src", "index.trb"), []byte(contracts), 0o644); err != nil {
				t.Fatal(err)
			}

			root := filepath.Join(workspace, "app")
			config := project.New(root, mode)
			config.SourceDir = "src"
			if config.Go != nil {
				config.Go.Module = "example.com/type-rb/web-client-package-test"
			}
			config.Packages["acme/contracts"] = project.PackageRequirement{Path: "../contracts"}
			if err := config.Save(); err != nil {
				t.Fatal(err)
			}
			if _, err := packageManager.ResolveTypeRBPackages(config, packageManager.TypeRBResolveOptions{}); err != nil {
				t.Fatal(err)
			}
			files := map[string]string{
				"src/main.trb": `import trb/web

def main()
	Web.serve()
	return
end
`,
				"src/routes/reports/[id].trb": `import { GetReportInput, ReportResponse } from acme/contracts
import { Context, Endpoint, Response, handles, input, response } from trb/web

def get(_context: Context): Response
	return Response.json({ "id" => 42 })
end

class GetReportEndpoint < Endpoint
	handles(get)
	input<GetReportInput>()
	response<ReportResponse>(status: 200)
end
`,
			}
			for relative, source := range files {
				path := filepath.Join(root, filepath.FromSlash(relative))
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			var stdout, stderr bytes.Buffer
			command := &CLI{Stdin: strings.NewReader(""), Stdout: &stdout, Stderr: &stderr}
			if status := command.Run([]string{"web", "client", "--config", config.Path}); status != 0 {
				t.Fatalf("status=%d stderr=%s", status, stderr.String())
			}
			for _, fragment := range []string{
				"import { GetReportInput, ReportResponse } from acme/contracts",
				"def get_report(input: GetReportInput",
				"encode_component(input.params.id.value().to_s())",
			} {
				if !strings.Contains(stdout.String(), fragment) {
					t.Fatalf("generated source does not contain %q:\n%s", fragment, stdout.String())
				}
			}
		})
	}
}

func TestWebClientReportsRouteLocalContractsAtTheirSource(t *testing.T) {
	root := t.TempDir()
	config := project.New(root, "go")
	config.SourceDir = "src"
	config.Go.Module = "example.com/type-rb/web-client-diagnostic-test"
	if err := config.Save(); err != nil {
		t.Fatal(err)
	}
	files := map[string]string{
		"src/main.trb": `import trb/web

def main()
	Web.serve()
	return
end
`,
		"src/routes/health.trb": `import { Context, Endpoint, Response, handles, response } from trb/web

record HealthResponse
	ok: Boolean
end

def get(_context: Context): Response
	return Response.json(HealthResponse.new(ok: true), 200)
end

class HealthEndpoint < Endpoint
	handles(get)
	response<HealthResponse>(status: 200)
end
`,
	}
	for relative, source := range files {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(source), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	var stdout, stderr bytes.Buffer
	command := &CLI{Stdin: strings.NewReader(""), Stdout: &stdout, Stderr: &stderr}
	if status := command.Run([]string{"web", "client", "--config", config.Path}); status == 0 {
		t.Fatalf("status=%d stdout=%s", status, stdout.String())
	}
	for _, fragment := range []string{"routes/health.trb", "shared module", "TRB4001"} {
		if !strings.Contains(stderr.String(), fragment) {
			t.Fatalf("stderr does not contain %q: %s", fragment, stderr.String())
		}
	}
}
